# Generated by Django 4.1 on 2024-06-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="姓名")),
                ("gender", models.IntegerField(verbose_name="性别")),
                ("age", models.IntegerField(verbose_name="年龄")),
                ("company", models.CharField(max_length=100, verbose_name="单位")),
                (
                    "isKnowAI",
                    models.BooleanField(default=False, verbose_name="是否接触过AI系统"),
                ),
                (
                    "isKnowFairness",
                    models.BooleanField(default=False, verbose_name="是否接触过公平性概念"),
                ),
                ("career", models.IntegerField(default=0, verbose_name="是否审计相关")),
            ],
        ),
    ]
