# Generated by Django 5.0.6 on 2024-06-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0002_rename_userinfo_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="career",
            field=models.IntegerField(
                choices=[(0, "审计工作者"), (1, "模型开发/研究人员"), (2, "普通用户(非技术人员)")],
                default=0,
                verbose_name="是否审计相关",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.IntegerField(
                choices=[(0, "男"), (1, "女"), (2, "未知")], verbose_name="性别"
            ),
        ),
    ]
